# _________             ____________________            ______ _____________             ________            _____________             _____
# __  ____/____________ ___  __/_  /___  __ )______________  /____  __ \__(_)_______________  __ \_________________  /__(_)___________ __  /_____________
# _  /    __  ___/  __ `/_  /_ _  __/_  __  |  __ \  __ \_  //_/_  /_/ /_  /___  __ \  _ \_  /_/ /_  ___/  _ \  __  /__  /_  ___/  __ `/  __/  _ \_  ___/
# / /___  _  /   / /_/ /_  __/ / /_ _  /_/ // /_/ / /_/ /  ,<  _  ____/_  / __  /_/ /  __/  ____/_  /   /  __/ /_/ / _  / / /__ / /_/ // /_ /  __/(__  )
# \____/  /_/    \__,_/ /_/    \__/ /_____/ \____/\____//_/|_| /_/     /_/  _  .___/\___//_/     /_/    \___/\__,_/  /_/  \___/ \__,_/ \__/ \___//____/
# /_/
#
# CraftBookPipePredicates - Developed by BlvckBytes <blvckbytes@gmail.com>
# Repository - https://github.com/BlvckBytes/CraftBookPipePredicates
# ASCII-Art - https://patorjk.com/software/taag/#p=display&f=Speed
#
# PRE-PROCESSOR-INPUT en_us.txt

commands:
  pipePredicate:
    name: 'pipepredicate'
    aliases:
      - pipr