# _________             ____________________            ______ _____________             ________            _____________             _____
# __  ____/____________ ___  __/_  /___  __ )______________  /____  __ \__(_)_______________  __ \_________________  /__(_)___________ __  /_____________
# _  /    __  ___/  __ `/_  /_ _  __/_  __  |  __ \  __ \_  //_/_  /_/ /_  /___  __ \  _ \_  /_/ /_  ___/  _ \  __  /__  /_  ___/  __ `/  __/  _ \_  ___/
# / /___  _  /   / /_/ /_  __/ / /_ _  /_/ // /_/ / /_/ /  ,<  _  ____/_  / __  /_/ /  __/  ____/_  /   /  __/ /_/ / _  / / /__ / /_/ // /_ /  __/(__  )
# \____/  /_/    \__,_/ /_/    \__/ /_____/ \____/\____//_/|_| /_/     /_/  _  .___/\___//_/     /_/    \___/\__,_/  /_/  \___/ \__,_/ \__/ \___//____/
# /_/
#
# CraftBookPipePredicates - Developed by BlvckBytes <blvckbytes@gmail.com>
# Repository - https://github.com/BlvckBytes/CraftBookPipePredicates
# ASCII-Art - https://patorjk.com/software/taag/#p=display<&f>=Speed

commands:
  pipePredicate:
    name: 'pipepredicate'
    aliases:
      - pipr
  pipeSearch:
    name: 'pps'

playerMessages:
  manualEditWhileInPredicateMode: '{lut.prefix} <&c>Du kannst das Schild im Prädikat-Modus nicht manuell bearbeiten!'
  commandPipePredicateUsage: '{lut.prefix} <&c>Benutze: /{label} \<<&e *for-action="action_names" *for-separator={<&7>,<space/>}>{action}</><&c>>'
  commandPipePredicateNoPiston: '{lut.prefix} <&c>Konnte keinen zum angeklickten Block zugehörigen Kolben auffinden.'
  commandPipePredicateNoSign: '{lut.prefix} <&c>Der zugehörige Kolben trägt kein valides Pipe-Schild an sich!'
  commandPipePredicateCannotEditSign: '{lut.prefix} <&c>Dir fehlen die nötigen Rechte um das Schild dieses Kolbens zu editieren!'
  commandPipePredicateCannotBuild: '{lut.prefix} <&c>Dir fehlen die nötigen Rechte um auf die Blöcke zuzugreifen!'
  commandPipePredicateNotLookingAtPipe: '{lut.prefix} <&c>Du schaust aktuell keine Pipe-Blöcke an; bitte schaue auf einen Kolben, einen Behälter, ein Schild oder ein Rohr!'
  commandPipePredicateNoPredicate: '{lut.prefix} <&c>Der zugehörige Kolben befindet sich aktuell nicht im Prädikat-Modus!'
  commandPipePredicatePredicateError: '{lut.prefix} <&c>Fehlerhaftes Prädikat: <&4>{error_message}'
  commandPipePredicateEmptyPredicate: '{lut.prefix} <&c>Bitte gib nur valide, nicht-leere Prädikate ein!'
  commandPipePredicateRemoveInit: '{lut.prefix} <&7>Interagiere mit einem <&a>Kolben, einem Behälter oder einem Schild <&7>um dessen Prädikat zu <&a>ENTFERNEN<&7>; <&a>sneake <&7>um den <&a>Mehrfachmodus <&7>zu aktivieren.'
  commandPipePredicateRemoveSuccess: '{lut.prefix} <&7>Das Prädikat <&a>{predicate} <&7>des zugehörigen Kolbens wurde <&a>erfolgreich entfernt<&7>!'
  commandPipePredicateSetInit: '{lut.prefix} <&7>Interagiere mit einem <&a>Kolben, einem Behälter oder einem Schild <&7>um dessen Prädikat auf <&a>{predicate} <&7>zu <&a>SETZEN<&7>; <&a>sneake <&7>um den <&a>Mehrfachmodus <&7>zu aktivieren.'
  commandPipePredicateSetSuccess: '{lut.prefix} <&7>Das Prädikat des zugehörigen Kolbens wurde <&a>erfolgreich <&7>auf <&a>{predicate} <&7>gesetzt<&7>!'
  commandPipePredicateMissingLanguage: '{lut.prefix} <&c>Bitte gib die Sprache des Prädikats als nächsten Parameter an!'
  commandPipePredicateUnknownLanguage: '{lut.prefix} <&c>Die Eingabe <&4>{input} <&c>repräsentiert keine bekannte Sprache!'
  commandPipePredicateInteractMultiEntered: '{lut.prefix} <&7>Du hast den <&a>Mehrfachmodus <&7>durch <&a>sneaking <&7>aktiviert - nun kann deine Aktion auf mehrere Kolben nacheinander angewandt werden; <&a>sneake erneut um den Modus zu verlassen<&7>.'
  commandPipePredicateInteractMultiExited: '{lut.prefix} <&7>Du hast den <&a>Mehrfachmodus <&7>durch <&a>erneutes sneaken <&7>wieder <&a>verlassen.'
  commandPipePredicateInteractMultiActionBarSignal: '<&a><&l>Du befindest dich im Mehrfachmodus; verlasse durchs sneaken.'
  commandPipePredicateInteractExpired: '{lut.prefix} <&c>Deine ausstehende Interaktion ist aufgrund von Inaktivität ausgelaufen.'
  commandPipePredicateGetInit: '{lut.prefix} <&7>Interagiere mit einem <&a>Kolben, einem Behälter oder einem Schild <&7>um dessen Prädikat <&7>zu <&a>LESEN<&7>; <&a>sneake <&7>um den <&a>Mehrfachmodus <&7>zu aktivieren.'
  commandPipePredicateGetPredicate: |
    {lut.prefix} <&7>Aktuell aktives Prädikat:<space/>
      <u>
        <hover-text value={<&a>Klicke auf das Prädikat, um einen Editierungsbefehl zu erhalten.}>
          <suggest-command value=`{set_command}`>
            <&a>{predicate}
      </u>
    <&7>, Sprache: <&a>{predicate_language}<&7>.
  commandPipePredicateGetError: '{lut.prefix} <&7>Der zugehörige Kolben befindet sich im Fehlerzustand: <&c>{predicate_error}'
  commandPipePredicateFrameLockInit: '{lut.prefix} <&7>Interagiere mit einem <&a>Kolben, einem Behälter oder einem Schild <&7>um <&a>Rahmen <&7>auf dem verbundenen Behälter zu <&a>SPERREN<&7>; <&a>sneake <&7>um den <&a>Mehrfachmodus <&7>zu aktivieren.'
  commandPipePredicateFrameUnlockInit: '{lut.prefix} <&7>Interagiere mit einem <&a>Kolben, einem Behälter oder einem Schild <&7>um <&a>Rahmen <&7>auf dem verbundenen Behälter zu <&a>ENTSPERREN<&7>; <&a>sneake <&7>um den <&a>Mehrfachmodus <&7>zu aktivieren.'
  commandPipePredicateFrameLockNoFrames: '{lut.prefix} <&c>Konnte keine Rahmen auf dem zugehörigen Behälter finden!'
  commandPipePredicateFrameLockAlreadyLocked: '{lut.prefix} <&c>Alle Rahmen auf dem zugehörigen Behälter sind bereits gesperrt!'
  commandPipePredicateFrameLockFramesLocked: '{lut.prefix} <&7>Alle <&a>Rahmen <&7>auf dem zugehörigen Behälter sind nun gesperrt (<&a>{frame_count} Stück<&7>).'
  commandPipePredicateFrameLockAlreadyUnlocked: '{lut.prefix} <&c>Alle Rahmen auf dem zugehörigen Behälter sind bereits entsperrt!'
  commandPipePredicateFrameLockFramesUnlocked: '{lut.prefix} <&7>Alle <&a>Rahmen <&7>auf dem zugehörigen Behälter sind nun entsperrt (<&a>{frame_count} Stück<&7>).'
  commandPipePredicateReloadSuccess: '{lut.prefix} <&7>Die Konfiguration des Plugins wurde <&a>erfolgreich neu geladen<&7>!'
  commandPipePredicateReloadFailure: '{lut.prefix} <&c>Während des Neuladeprozesses der Konfiguration trat ein Fehler auf; bitte überprüfe die Konsole!'
  commandPipePredicateSearchInSession: '{lut.prefix} <&c>Es ist aktuell bereits eine Suche im Gange!'
  commandPipePredicateSearchExceededPipes: '{lut.prefix} <&e>Das Limit von <&6>{limit} Rohrblöcken <&e>wurde überschritten; stoppe vorzeitig!'
  commandPipePredicateSearchExceededPistons: '{lut.prefix} <&e>Das Limit von <&6>{limit} Ausgangskolben <&e>wurde überschritten; stoppe vorzeitig!'
  commandPipePredicateSearchExceededRetry: '{lut.prefix} <&e>Das Limit von <&6>{limit} Ladeversuchen <&e>wurde überschritten; stoppe vorzeitig!'
  commandPipePredicateSearchNoContainers: '{lut.prefix} <&c>Es konnten keine Behälter an Ausgangskolben gefunden werden (<&4>{piston_count} Kolben<&c>, <&4>{tube_count} Rohrblöcke<&c>)!'
  commandPipePredicateSearchActionbarWarmup: '<&6>[Pipe] Wärme auf... {tube_count} Rohre, {piston_count} Kolben'
  commandPipePredicateSearchNoResults: |
    {lut.prefix} <&c>Die Suche <&4>{predicate} <&c>ergab bei <&4>{item_count} Items <&c>keine Ergebnisse (<&4>{piston_count} Kolben<&c>, <&4>{tube_count} Rohrblöcke<&c>, <u><hover-text value={
      <&c *for-entry="container_counts" *for-separator={<&7>,<space/>}>{entry.count}x <translate key=`{entry.translation_key}`/>
    }><&4>{total_container_count} Behälter</u><&c>)!
  commandPipePredicateSearchShowingResults: |
    {lut.prefix} <&7>Die Suche <&a>{predicate} <&7>lieferte bei insgesamt <&a>{item_count} <&7>Items <&a>{match_count} <&7>Übereinstimmungen (<&a>{piston_count} Kolben<&7>, <&a>{tube_count} Rohrblöcke<&7>, <u><hover-text value={
      <&a *for-entry="container_counts" *for-separator={<&7>,<space/>}>{entry.count}x <translate key=`{entry.translation_key}`/>
    }><&a>{total_container_count} Behälter</u><&7>).
  commandPipePredicateSearchGetItemContainerAbsent: '{lut.prefix} <&c>Der Behälter <&4>existiert <&c>inzwischen nicht mehr; breche ab!'
  commandPipePredicateSearchGetItemContainerSizeChanged: '{lut.prefix} <&c>Die <&4>Größe <&c>des Behälters hat sich inzwischen verändert; breche ab!'
  commandPipePredicateSearchGetItemMoved: '{lut.prefix} <&c>Das Item <&4><tr key=`{item_type_key}`/> <&c>wurde inzwischen <&4>bewegt<&c>; breche ab!'
  commandPipePredicateSearchGetItemSuccess: '{lut.prefix} <&7>Vom Item <&a><tr key=`{item_type_key}`/> <&7>wurden insgesamt <&a>{lut.amount_display} <&7>ausgehändigt.'
  commandPipePredicateSearchGetNoSpace: '{lut.prefix} <&c>Du hast keinen Platz im Inventar!'
  commandPipePredicateSearchContainerOpened: '{lut.prefix} <&7>Du hast nun Einsicht in den Behälter bei <&a>{container_x} {container_y} {container_z}<&7>.'
  commandPipePredicateSearchContainerTeleportObstructed: '{lut.prefix} <&c>Der Behälter ist an allen Seiten durch unpassierbare Blöcke versperrt!'
  commandPipePredicateSearchContainerTeleported: '{lut.prefix} <&7>Du wurdest zum Behälter bei <&a>{container_x} {container_y} {container_z} <&7>teleportiert.'
  commandPipePredicateVisualizeInternalError: '{lut.prefix} <&c>Während des Visualisierens der Pipe, ausgehend von <&4>{origin_x} {origin_y} {origin_z}<&c>, trat ein interner Fehler auf; bitte melden!'
  commandPipePredicateVisualizeRanIntoLimit: '{lut.prefix} <&7>Das Visualisierungslimit von <&6>{cube_limit} <&7>Blöcken wurde überschritten; <&6>stoppe vorzeitig<&7>!'
  commandPipePredicateVisualizeSuccess: '{lut.prefix} <&7>Zeige <&a>{cube_count} <&7>visualisierte Pipe-Blöcke ausgehend von <&a>{origin_x} {origin_y} {origin_z}<&7> an.'
  commandPipePredicateVisualizeNoVisualization: '{lut.prefix} <&c>Es wird aktuell keine Visualisierung angezeigt, die entfernt werden könnte!'
  commandPipePredicateVisualizeClearedPriorVisualization: '{lut.prefix} <&7>Die <&6>vorherige Visualisierung <&7>wurde automatisch <&6>entfernt<&7>!'
  commandPipePredicateVisualizeClearedVisualization: '{lut.prefix} <&7>Die angezeigte Visualisierung wurde <&a>entfernt<&7>.'
  missingPermissionPipePredicateCommand: '{lut.prefix} <&c>Dir fehlen die nötigen Rechte um diesen Befehl zu benutzen!'

resultDisplay:
  title: '<&8>Pipesuche <&e>{current_page}<&8>/<&e>{number_pages}'
  rows: 6
  paginationSlots: '0..44'
  items:
    previousPage:
      slots: 'last_slot - 8'
      type: PLAYER_HEAD
      textures: '{lut.textures[current_page > 1 then "ARROW_LEFT" else "ARROW_LEFT_RED"]}'
      name: |
        <reset>
          <container *if="current_page > 1"><&8>» <&6>Vorherige Seite <&8>«</container>
          <container *else><&8>» <&c>Keine vorherige Seite <&8>«</container>
      lore: |
        <reset>
          <br/>
          {lut.spacer}<br/>
          <&8>➥ <&e>Linksklick <&7>Navigiere zur vorherigen Seite><br/>
          <&8>➥ <&e>Rechtsklick <&7>Springe zur ersten Seite><br/>
          {lut.spacer}
    nextPage:
      slots: 'last_slot'
      type: PLAYER_HEAD
      textures: '{lut.textures[current_page < number_pages then "ARROW_RIGHT" else "ARROW_RIGHT_RED"]}'
      name: |
        <reset>
          <container *if="current_page < number_pages"><&8>» <&6>Nächste Seite <&8>«</container>
          <container *else><&8>» <&c>Keine nächste Seite <&8>«</container>
      lore: |
        <reset>
          <br/>
          {lut.spacer}<br/>
          <&8>➥ <&e>Linksklick <&7>Navigiere zur nächsten Seite<br/>
          <&8>➥ <&e>Rechtsklick <&7>Springe zur letzten Seite<br/>
          {lut.spacer}
    stackRepresentativePatch:
      lore: |
        <reset>
          <br/>
          {lut.spacer}<br/>
          <&8>♦ <&7>Koordinaten: <&e>{container_x} {container_y} {container_z}<br/>
          <&8>♦ <&7>Slot: <&e>{slot}<br/>
          {lut.spacer}<br/>
          <&8>➥ <&e>Linksklick <&7>Hinteleportieren<br/>
          <&8>➥ <&e>Werfen <&7>Ins Inventar bewegen<br/>
          <&8>➥ <&e>Alle Werfen <&7>Behälter öffnen<br/>
          {lut.spacer}
    collectionRepresentativePatch:
      lore: |
        <reset>
          <br/>
          {lut.spacer}<br/>
          <&8>♦ <&7>Anzahl: <&e *let-display_dks>{lut.amount_display}</><br/>
          {lut.spacer}<br/>
          <&8>➥ <&e>Linksklick <&7>Einzelstacks anzeigen<br/>
          <&8>➥ <&e>Werfen <&7>Einen Stack ins Inventar bewegen<br/>
          <&8>➥ <&e>Alle Werfen <&7>Inventar mit Items befüllen<br/>
          {lut.spacer}
    filler:
      slots: '(last_slot - 7)..(last_slot - 1)'
      type: BLACK_STAINED_GLASS_PANE
      name: " "

defaultPredicateLanguage: 'GERMAN_DE'

# Fully qualified names of classes which represent listeners for the SignChangeEvent - an event
# called to determine whether the player has the privileges to alter a pipe's state.
fakeEventSkippedListeners:
  # Avoid the "Pipe created!" message; this listener has no say in protection either
  - com.sk89q.craftbook.mechanics.pipe.Pipes

# File-global component lookup-table
cLut:
  prefix: '<&7>[<&6>Pipr<&7>]'
  spacer: '<&8><&m>{" " ** 55}'
  amount_display: |
    <container *if="number_stacks > 0">
      {number_stacks}x {stack_size}
      <container *if="has(display_dks) and number_stacks > 1">
        <container *if="number_double_chests eq 1"><&7> (</>eine DK<&7>)</container>
        <container *else-if="number_double_chests > 0">
          <&7> (</><number [value]="number_double_chests" format="0.0" locale="de_AT" rounding="UP"/> DKs<&7>)
        </container>
      </container>
    </container>
    <container *if="single_items > 0">
      <&7 *if="number_stacks > 0"> und </>
      {single_items} Stück
    </container>

# File-global scalar lookup-table
sLut:
  textures:
    ARROW_LEFT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODU1MGI3Zjc0ZTllZDc2MzNhYTI3NGVhMzBjYzNkMmU4N2FiYjM2ZDRkMWY0Y2E2MDhjZDQ0NTkwY2NlMGIifX19'
    ARROW_LEFT_RED: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjg0ZjU5NzEzMWJiZTI1ZGMwNThhZjg4OGNiMjk4MzFmNzk1OTliYzY3Yzk1YzgwMjkyNWNlNGFmYmEzMzJmYyJ9fX0='
    ARROW_RIGHT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTYzMzlmZjJlNTM0MmJhMThiZGM0OGE5OWNjYTY1ZDEyM2NlNzgxZDg3ODI3MmY5ZDk2NGVhZDNiOGFkMzcwIn19fQ=='
    ARROW_RIGHT_RED: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmNmZTg4NDVhOGQ1ZTYzNWZiODc3MjhjY2M5Mzg5NWQ0MmI0ZmMyZTZhNTNmMWJhNzhjODQ1MjI1ODIyIn19fQ=='