# _________             ____________________            ______ _____________             ________            _____________             _____
# __  ____/____________ ___  __/_  /___  __ )______________  /____  __ \__(_)_______________  __ \_________________  /__(_)___________ __  /_____________
# _  /    __  ___/  __ `/_  /_ _  __/_  __  |  __ \  __ \_  //_/_  /_/ /_  /___  __ \  _ \_  /_/ /_  ___/  _ \  __  /__  /_  ___/  __ `/  __/  _ \_  ___/
# / /___  _  /   / /_/ /_  __/ / /_ _  /_/ // /_/ / /_/ /  ,<  _  ____/_  / __  /_/ /  __/  ____/_  /   /  __/ /_/ / _  / / /__ / /_/ // /_ /  __/(__  )
# \____/  /_/    \__,_/ /_/    \__/ /_____/ \____/\____//_/|_| /_/     /_/  _  .___/\___//_/     /_/    \___/\__,_/  /_/  \___/ \__,_/ \__/ \___//____/
# /_/
#
# CraftBookPipePredicates - Developed by BlvckBytes <blvckbytes@gmail.com>
# Repository - https://github.com/BlvckBytes/CraftBookPipePredicates
# ASCII-Art - https://patorjk.com/software/taag/#p=display&f=Speed
#
# PRE-PROCESSOR-INPUT en_us.txt

commands:
  pipePredicate:
    name: 'pipepredicate'
    aliases:
      - pipr

playerMessages:
  manualEditWhileInPredicateMode: '@{MESSAGE-MANUAL-EDIT-WHILE-IN-PREDICATE-MODE(prefix=lut["MESSAGE_PREFIX"])}'
  commandPipePredicateUsage: |
    actions_list = iter_cat(action_names, (action) => @{MESSAGE-COMMAND-PIPE-PREDICATE-USAGE-ACTION-PREFIX} & action, @{MESSAGE-COMMAND-PIPE-PREDICATE-USAGE-ACTION-SEPARATOR})
    @{MESSAGE-COMMAND-PIPE-PREDICATE-USAGE(prefix=lut["MESSAGE_PREFIX"])}
  commandPipePredicateNoPiston: '@{MESSAGE-COMMAND-PIPE-PREDICATE-NO-PISTON(prefix=lut["MESSAGE_PREFIX"])}'
  commandPipePredicateNoSign: '@{MESSAGE-COMMAND-PIPE-PREDICATE-NO-SIGN(prefix=lut["MESSAGE_PREFIX"])}'
  commandPipePredicateCannotEditSign: '@{MESSAGE-COMMAND-PIPE-PREDICATE-CANNOT-EDIT-SIGN(prefix=lut["MESSAGE_PREFIX"])}'
  commandPipePredicateNoPredicate: '@{MESSAGE-COMMAND-PIPE-PREDICATE-NO-PREDICATE(prefix=lut["MESSAGE_PREFIX"])}'
  commandPipePredicateEmptyPredicate: '@{MESSAGE-COMMAND-PIPE-PREDICATE-EMPTY-PREDICATE(prefix=lut["MESSAGE_PREFIX"])}'
  commandPipePredicateRemoveSuccess: '@{MESSAGE-COMMAND-PIPE-PREDICATE-REMOVE-SUCCESS(prefix=lut["MESSAGE_PREFIX"])}'
  commandPipePredicateSetSuccess: '@{MESSAGE-COMMAND-PIPE-PREDICATE-SET-SUCCESS(prefix=lut["MESSAGE_PREFIX"])}'
  commandPipePredicateSetLocalizedMissingLanguage: '@{MESSAGE-COMMAND-PIPE-PREDICATE-SET-LOCALIZED-MISSING-LANGUAGE(prefix=lut["MESSAGE_PREFIX"])}'
  commandPipePredicateSetLocalizedUnknownLanguage: '@{MESSAGE-COMMAND-PIPE-PREDICATE-SET-LOCALIZED-UNKNOWN-LANGUAGE(prefix=lut["MESSAGE_PREFIX"])}'
  commandPipePredicateGetPredicateDefaultLanguage: '@{MESSAGE-COMMAND-PIPE-PREDICATE-GET-PREDICATE-DEFAULT-LANGUAGE(prefix=lut["MESSAGE_PREFIX"])}'
  commandPipePredicateGetPredicateOtherLanguage: '@{MESSAGE-COMMAND-PIPE-PREDICATE-GET-PREDICATE-OTHER-LANGUAGE(prefix=lut["MESSAGE_PREFIX"])}'
  commandPipePredicateGetPredicateHover: '@{MESSAGE-COMMAND-PIPE-PREDICATE-GET-PREDICATE-HOVER(prefix=lut["MESSAGE_PREFIX"])}'
  commandPipePredicateGetError: '@{MESSAGE-COMMAND-PIPE-PREDICATE-GET-ERROR(prefix=lut["MESSAGE_PREFIX"])}'
  commandPipePredicateReloadSuccess: '@{MESSAGE-COMMAND-PIPE-PREDICATE-RELOAD-SUCCESS(prefix=lut["MESSAGE_PREFIX"])}'
  commandPipePredicateReloadFailure: '@{MESSAGE-COMMAND-PIPE-PREDICATE-RELOAD-FAILURE(prefix=lut["MESSAGE_PREFIX"])}'

  missingPermissionPipePredicateCommand: '@{MESSAGE-MISSING-PERMISSION-PIPE-PREDICATE-COMMAND(prefix=lut["MESSAGE_PREFIX"])}'
  missingPermissionPipePredicateRead: '@{MESSAGE-MISSING-PERMISSION-PIPE-PREDICATE-READ(prefix=lut["MESSAGE_PREFIX"])}'
  missingPermissionPipePredicateModify: '@{MESSAGE-MISSING-PERMISSION-PIPE-PREDICATE-MODIFY(prefix=lut["MESSAGE_PREFIX"])}'
  missingPermissionPipePredicateReload: '@{MESSAGE-MISSING-PERMISSION-PIPE-PREDICATE-RELOAD(prefix=lut["MESSAGE_PREFIX"])}'

defaultPredicateLanguage: 'ENGLISH_US'

# Fully qualified names of classes which represent listeners for the SignChangeEvent - an event
# called to determine whether the player has the privileges to alter a pipe's state.
fakeEventSkippedListeners:
  # Avoid the "Pipe created!" message; this listener has no say in protection either
  - com.sk89q.craftbook.mechanics.pipe.Pipes

# File-global lookup table
lut:
  MESSAGE_PREFIX: '@{MESSAGE-PREFIX}'
