name: PipePredicates
main: me.blvckbytes.pipe_predicates.PipePredicatesPlugin
version: 0.0.3
author: BlvckBytes
api-version: 1.14
depend: [BBTweaks, ItemPredicateParser, ProtocolLib]
softdepend: [floodgate]
commands:
  pipepredicate:
  pipesearch:
  pipeteleport:
permissions:
  pipepredicates.command.pipepredicate.reload:
    description: 'Reload the plugin''s configuration'
    default: op
  pipepredicates.command.pipepredicate.search:
    description: 'Search the whole pipe using predicates'
    default: op
  pipepredicates.command.pipepredicate.capacities:
    description: 'Analyze the remaining capacities of a pipe''s containers'
    default: op
  pipepredicates.command.pipepredicate.locate-predicates:
    description: 'Search for predicates in a pipe via string-contains'
    default: op
  pipepredicates.auto-init-signs:
    description: 'Automatically initialize blank signs to a valid pipe sign'
    default: op